// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔥 Web 플랫폼 설정 (실제 값으로 업데이트 완료!)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjjnrZI566ZLK75Vz1nfVZGfGJhoQNdMo',
    appId: '1:79236393316:web:8d8fed1d383d2bdaf7b271',
    messagingSenderId: '79236393316',
    projectId: 'rehab-nexus-korea',
    authDomain: 'rehab-nexus-korea.firebaseapp.com',
    storageBucket: 'rehab-nexus-korea.firebasestorage.app',
    measurementId: 'G-71N75WV6ZC',
  );

  // 🔥 Android 플랫폼 설정 (google-services.json 기반)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5SYKPtvyTVMIMOO_AVIOodGZEj9jNHpM',
    appId: '1:79236393316:android:b270268491b95feaf7b271',
    messagingSenderId: '79236393316',
    projectId: 'rehab-nexus-korea',
    storageBucket: 'rehab-nexus-korea.firebasestorage.app',
  );

  // 🔥 iOS 플랫폼 설정 (나중에 추가 가능)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5SYKPtvyTVMIMOO_AVIOodGZEj9jNHpM',
    appId: '1:79236393316:ios:PLACEHOLDER',
    messagingSenderId: '79236393316',
    projectId: 'rehab-nexus-korea',
    storageBucket: 'rehab-nexus-korea.firebasestorage.app',
    iosBundleId: 'com.rehabnexus.rehab',
  );

  // 🔥 macOS 플랫폼 설정 (나중에 추가 가능)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5SYKPtvyTVMIMOO_AVIOodGZEj9jNHpM',
    appId: '1:79236393316:macos:PLACEHOLDER',
    messagingSenderId: '79236393316',
    projectId: 'rehab-nexus-korea',
    storageBucket: 'rehab-nexus-korea.firebasestorage.app',
    iosBundleId: 'com.rehabnexus.rehab',
  );
}
